//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisdom.HomeAutomation.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeAutomationEntities : DbContext
    {
        public HomeAutomationEntities()
            : base("name=HomeAutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_CommandType> t_CommandType { get; set; }
        public virtual DbSet<t_DetailScheme> t_DetailScheme { get; set; }
        public virtual DbSet<t_HomeAppliances> t_HomeAppliances { get; set; }
        public virtual DbSet<t_Scheme> t_Scheme { get; set; }
        public virtual DbSet<v_DtailScheme> v_DtailScheme { get; set; }
    }
}
