//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisdom.HomeAutomation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CommandType
    {
        public int Id { get; set; }
        public string CommandName { get; set; }
        public int HomeApplianceId { get; set; }
        public int Port { get; set; }
    
        public virtual t_HomeAppliances t_HomeAppliances { get; set; }
    }
}
