//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisdom.HomeAutomation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DetailScheme
    {
        public long Id { get; set; }
        public long SchemeId { get; set; }
        public Nullable<int> HomeAppliancesId { get; set; }
        public int WaitTime { get; set; }
        public int RunTime { get; set; }
    
        public virtual t_HomeAppliances t_HomeAppliances { get; set; }
        public virtual t_Scheme t_Scheme { get; set; }
    }
}
