//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisdom.HomeAutomation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Scheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Scheme()
        {
            this.t_DetailScheme = new HashSet<t_DetailScheme>();
        }
    
        public long Id { get; set; }
        public string SchemeName { get; set; }
        public bool state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_DetailScheme> t_DetailScheme { get; set; }
    }
}
