//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisdom.HomeAutomation.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DtailScheme
    {
        public long DetailSchemeId { get; set; }
        public long SchemeId { get; set; }
        public string SchemeName { get; set; }
        public int HomeAppliancesId { get; set; }
        public string HomeAppliancesName { get; set; }
        public int WaitTime { get; set; }
        public int RunTime { get; set; }
    }
}
